module.exports =
  DECREMENT_PRODUCT: 'DECREMENT_PRODUCT'
  INCREMENT_PRODUCT: 'INCREMENT_PRODUCT'
  SELECT_USER: 'SELECT_USER'
  SET_USERS: 'SET_USERS'
  SET_PRODUCTS: 'SET_PRODUCTS'
  STATUS: 'STATUS'
